apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-admin-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - '*'
  verbs:
  - '*'